package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"

	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/models"
)

// MyActivityLogs is the resolver for the myActivityLogs field.
func (r *queryResolver) MyActivityLogs(ctx context.Context, page *int, limit *int, typeArg *string) (*models.PaginatedActivityLogs, error) {
	// 1. Get User ID from context (authenticated route)
	userID, ok := ctx.Value(AuthUserUUIDKey).(string)
	if !ok || userID == "" {
		return nil, ErrNotAuthenticated
	}

	// 2. Apply defaults (Req 1.14.3.2)
	p, l := 1, 10
	if page != nil {
		p = *page
	}
	if limit != nil {
		l = *limit
	}

	// 3. Call the core service
	paginatedResult, err := r.Resolver.activityLogService.GetMyLogs(ctx, userID, p, l, typeArg)
	if err != nil {
		r.Resolver.logger.Error().Err(err).Str("user_id", userID).Msg("Failed to get activity logs")
		return nil, errors.New("could not retrieve activity logs")
	}

	// 4. Map domain models to GraphQL models (Req 1.14.3.5)
	return mapDomainToGqlPaginatedLogs(paginatedResult), nil
}
