package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"

	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/generated"
	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/models"
	"github.com/ipincamp/srikandi-sehat/internal/core/service"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input models.RegisterInput) (*models.AuthResponse, error) {
	// 1. Call the injected authService
	authRes, err := r.authService.Register(ctx, input.Name, input.Email, input.Password)
	if err != nil {
		// Log the error
		log := r.logger.Warn().Err(err).Str("email", input.Email).Str("mutation", "Register")

		// Provide context-specific logs for known business errors
		if errors.Is(err, service.ErrEmailExists) {
			log.Msg("Registration failed: Email exists")
		} else {
			log.Msg("Registration failed: Unexpected service error")
		}

		// 2. Errors from the service are passed to GraphQL.
		return nil, err
	}

	// 3. Convert from the service's 'ports.AuthResponse' to the GraphQL 'models.AuthResponse'.
	return &models.AuthResponse{
		AccessToken:  authRes.AccessToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input models.LoginInput) (*models.AuthResponse, error) {
	// 1. Call the injected authService
	authRes, err := r.authService.Login(ctx, input.Email, input.Password)
	if err != nil {
		// Log the error
		log := r.logger.Warn().Err(err).Str("email", input.Email).Str("mutation", "Login")

		if errors.Is(err, service.ErrInvalidCredentials) {
			log.Msg("Login failed: Invalid credentials")
		} else {
			log.Msg("Login failed: Unexpected service error")
		}

		// 2. Errors from the service are passed to GraphQL.
		return nil, err
	}

	// 3. Convert from the service type to the GraphQL model type.
	return &models.AuthResponse{
		AccessToken:  authRes.AccessToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
