package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"fmt"

	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/generated"
	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/models"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input models.UpdateProfileInput) (*models.User, error) {
	// 1. Get User ID from context (this is an authenticated route)
	userID, ok := ctx.Value(AuthUserUUIDKey).(string)
	if !ok || userID == "" {
		return nil, ErrNotAuthenticated
	}

	// 2. Validation Step
	vInput := updateProfileInputValidation{
		Name: input.Name,
	}
	if err := validate.Struct(vInput); err != nil {
		return nil, formatValidationErrors(err)
	}

	// 3. Call the core service
	domainUser, err := r.Resolver.userService.UpdateProfile(ctx, userID, input.Name)
	if err != nil {
		r.Resolver.logger.Error().Err(err).Str("user_id", userID).Msg("Failed to update profile")
		return nil, fmt.Errorf("profile update failed")
	}

	// 4. Map domain model to GraphQL model and return
	return mapDomainUserToGqlUser(domainUser), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	// 1. Ambil User ID dari context (yang di-inject oleh middleware/auth.go)
	userID, ok := ctx.Value(AuthUserUUIDKey).(string)
	if !ok || userID == "" {
		r.Resolver.logger.Warn().Msg("No user ID in context for 'me' query")
		return nil, ErrNotAuthenticated
	}

	r.Resolver.logger.Info().Str("user_id", userID).Msg("Processing 'me' query")

	// 2. Panggil Core Service (Logika Bisnis)
	domainUser, err := r.Resolver.userService.GetByID(ctx, userID)
	if err != nil {
		// Error bisa jadi 'user not found'
		r.Resolver.logger.Error().Err(err).Str("user_id", userID).Msg("Failed to get user from service")
		return nil, fmt.Errorf("failed to retrieve user data")
	}

	// 3. Konversi dari domain.User (bisnis) ke models.User (GraphQL)
	// 'models' adalah DTO (Data Transfer Object) untuk lapisan API.
	gqlUser := mapDomainUserToGqlUser(domainUser)

	return gqlUser, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
