package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"
	"time"

	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/generated"
	"github.com/ipincamp/srikandi-sehat/internal/adapters/driving/graphql/models"
	"github.com/ipincamp/srikandi-sehat/internal/core/service"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	// 1. Extract user UUID from context.
	// This is set by the (unseen) auth middleware.
	uuid, ok := ctx.Value(AuthUserUUIDKey).(string)
	if !ok || uuid == "" {
		r.logger.Warn().Msg("Resolver 'Me' failed: No user UUID in context")
		// This error signals that the auth middleware likely failed or wasn't run.
		return nil, ErrNotAuthenticated
	}

	// 2. Call the injected userService
	user, err := r.userService.GetUserByID(ctx, uuid)
	if err != nil {
		log := r.logger.Warn().Err(err).Str("uuid", uuid)
		if errors.Is(err, service.ErrUserNotFound) {
			log.Msg("Authenticated user not found in DB")
		} else {
			log.Msg("Failed to fetch user profile")
		}
		return nil, err
	}

	// 3. Convert from the service's 'domain.User' to the GraphQL 'models.User'.
	return &models.User{
		UUID:      user.UUID,
		Name:      user.Name,
		Email:     user.Email,
		CreatedAt: user.CreatedAt.Format(time.RFC3339), // Format as ISO 8601 string
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
