# Config file for Air - https://github.com/cosmtrek/air
#
# Create a `.air.toml` file in your project root to configure Air.
#
# This is a minimal configuration file. You can view the full configuration
# options here: https://github.com/cosmtrek/air/blob/master/air_example.toml

root = "."
tmp_dir = "tmp"

[build]
# Command to build your app.
# The `main.go` file is in `cmd/api/main.go`.
cmd = "go build -o ./tmp/srikandisehat ./cmd/api/main.go"

# Binary file to run.
bin = "tmp/srikandisehat"

# Command to run the binary.
# We pass the environment variables here, similar to your `run-dev` command.
full_bin = "ENV=development TZ=Asia/Jakarta ./tmp/srikandisehat"

# Watch these file extensions.
include_ext = ["go", "tpl", "tmpl", "html"]

# Ignore these directories.
exclude_dir = ["assets", "tmp", "vendor", "bin", "migrations"]

# Watch these directories.
include_dir = []

# Exclude these files.
exclude_file = []

# Log name for the build process.
log = "air-build.log"

# Delay in milliseconds before restarting the app.
delay = 1000 # 1s

# Stop on first error.
stop_on_error = true

# Kill delay in milliseconds.
kill_delay = 500 # 0.5s

[log]
# Show log time
time = true

[color]
# Customize colors.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
