// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ActivityLog struct {
	ID          string  `json:"id"`
	Action      string  `json:"action"`
	TargetTable *string `json:"target_table,omitempty"`
	TargetID    *string `json:"target_id,omitempty"`
	Changes     *string `json:"changes,omitempty"`
	IPAddress   *string `json:"ip_address,omitempty"`
	UserAgent   *string `json:"user_agent,omitempty"`
	Timestamp   string  `json:"timestamp"`
}

type ActivityLogPagination struct {
	TotalItems  int `json:"total_items"`
	TotalPages  int `json:"total_pages"`
	CurrentPage int `json:"current_page"`
	PerPage     int `json:"per_page"`
}

type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type ChangePasswordInput struct {
	CurrentPassword   string `json:"current_password"`
	NewPassword       string `json:"new_password"`
	LogoutAllSessions *bool  `json:"logout_all_sessions,omitempty"`
}

type DeleteMyAccountInput struct {
	CurrentPassword string `json:"current_password"`
}

type DisableAccountInput struct {
	CurrentPassword string `json:"current_password"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PaginatedActivityLogs struct {
	Data []*ActivityLog         `json:"data"`
	Meta *ActivityLogPagination `json:"meta"`
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RequestAccountDeletionInput struct {
	CurrentPassword string `json:"current_password"`
}

type RequestEmailChangeInput struct {
	NewEmail        string `json:"new_email"`
	CurrentPassword string `json:"current_password"`
}

type ResetPasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"new_password"`
}

type UpdateProfileInput struct {
	Name string `json:"name"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
